name: lisa_flutter
description: L.I.S.A. cross platform application

version: 0.0.1+2

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  sentry: ^3.0.1
  file_chooser:
    path: ../../../flutter-desktop-embedding/plugins/file_chooser
  flutter_staggered_animations: ^0.1.2
  keyboard_avoider: ^0.1.2
  flutter_speech: ^1.1.0
    #path: '../../../flutter_speech_recognition'
  lisa_server_sdk:
    path: '../api'
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  crypted_preferences: ^0.0.2
  connectivity: ^0.4.8+6
  image_picker: ^0.6.7+2
  flutter_staggered_grid_view: ^0.3.0
  mobx: ^1.2.1+1
  flutter_mobx: ^1.1.0+1
  remote_ui: ^0.0.8
  remote_form: ^0.0.2
  remote_color_picker: ^0.0.2
  remote_ip_camera: ^1.1.3
  remote_image_button: ^0.0.4
  proxy_layout: ^2.1.0
  provider: ^4.1.3
  flare_splash_screen: ^3.0.1
    #path: '../../../../StudioProjects/flare_splash_screen'
  flare_checkbox: ^1.0.3
  flutter_hooks: ^0.10.0
  multicast_lock: ^0.0.5
  path_provider: ^1.6.11
  intl_translation: ^0.17.7
  flare_flutter: ^2.0.4
  toast: ^0.1.5
  #firebase_analytics: ^3.0.1

  cupertino_icons: ^0.1.3

dev_dependencies:
  mobx_codegen: ^1.1.0+1
  build_runner: ^1.7.0
  flutter_test:
    sdk: flutter

dependency_overrides:
  http_multi_server: ^2.2.0
  remote_form:
    path: '../../../remote_ui/packages/remote_form'
  remote_color_picker:
    path: '../../../remote_ui/packages/remote_color_picker'
  remote_ip_camera:
    path: '../../../remote_ui/packages/remote_ip_camera'
  flutter_mjpeg:
    path: '../../../flutter_mjpeg'
  remote_image_button:
    path: '../../../remote_ui/packages/remote_image_button'
  remote_ui:
    path: '../../../remote_ui/packages/remote_ui'


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/animations/

  fonts:
     - family: Raleway
       fonts:
         - asset: assets/fonts/Raleway-Regular.ttf
         - asset: assets/fonts/Raleway-Italic.ttf
           style: italic
         - asset: assets/fonts/Raleway-Bold.ttf
           weight: 700
         - asset: assets/fonts/Raleway-SemiBold.ttf
           weight: 600
