name: lisa_flutter
description: L.I.S.A. cross platform application

version: 0.1.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  local_auth: ^1.1.9
  flutter_slidable: ^1.1.0
  sleek_circular_slider: ^2.0.1
  flutter_secure_storage: ^5.0.2
  collection: ^1.15.0
  dio:
  web_socket_channel: ^2.1.0
  built_value:
  built_collection:
  flutter_vector_icons: ^1.0.0
  nymea_network_manager: ^0.1.0
    #path: '../../../nymea_network_manager'
  flutter_sickchill: ^0.1.1
    #path: '../../../flutter_sickchill'
  flutter_transmission: ^0.1.2
    #path: '../../../flutter_transmission'
  sentry_flutter: ^6.2.2
  logging: ^1.0.2
  file_picker: ^4.3.0
  flutter_svg: ^1.0.0
  file_selector: ^0.8.2
  file_selector_macos: ^0.0.4
  #file_selector_macos:
  #  path: ../../../flutter-desktop-embedding/plugins/file_selector/file_selector_macos
  flutter_staggered_animations: ^1.0.0
  flutter_speech: ^2.0.0
  pubspec_parse: ^1.2.0
    #path: '../../../flutter_speech_recognition'
  lisa_server_sdk:
    path: '../api'
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.0.11
  connectivity: ^3.0.6
  wifi_info_flutter: ^2.0.2
  image_picker: ^0.8.4
  flutter_staggered_grid_view: ^0.4.1
  mobx: ^2.0.6
  flutter_mobx: ^2.0.3
  remote_ui: ^0.1.1
  remote_form: ^0.1.0
  flutter_colorpicker: ">=1.0.3 <2.0.0"
  remote_color_picker: ^0.1.1
  remote_ip_camera: ^2.0.0
  remote_image_button: ^0.1.1
  proxy_layout: ^3.0.0
  provider: ^6.0.1
  flare_splash_screen: ^4.0.0
    #path: '../../../../StudioProjects/flare_splash_screen'
  flare_checkbox: ^2.0.0+1
  flutter_hooks: ^0.18.1
  android_multicast_lock: ^1.0.2
    #path: '../../../android_multicast_lock'
  path_provider: ^2.0.8
  flare_flutter: ^3.0.2
  #firebase_analytics: ^3.0.1

  cupertino_icons: ^1.0.4

dev_dependencies:
  flutter_lints: ^1.0.4
  mobx_codegen: ^2.0.5
  build_runner: ^2.0.1
  flutter_test:
    sdk: flutter

dependency_overrides:
  #remote_form:
  #  path: '../../../remote_ui/packages/remote_form'
  #remote_color_picker:
  #  path: '../../../remote_ui/packages/remote_color_picker'
  #remote_ip_camera:
  #  path: '../../../remote_ui/packages/remote_ip_camera'
#  flutter_mjpeg:
#    path: '../../../flutter_mjpeg'
  #remote_image_button:
  #  path: '../../../remote_ui/packages/remote_image_button'
  #remote_ui:
    #path: '../../../remote_ui/packages/remote_ui'
  #flutter_transmission:
  #    path: '../../../flutter_transmission'
  #flutter_sickchill:
  #      path: '../../../flutter_sickchill'


flutter:

  uses-material-design: true

  assets:
    - pubspec.yaml
    - assets/images/
    - assets/images/widgets/
    - assets/animations/

  fonts:
     - family: Raleway
       fonts:
         - asset: assets/fonts/Raleway-Regular.ttf
         - asset: assets/fonts/Raleway-Italic.ttf
           style: italic
         - asset: assets/fonts/Raleway-Bold.ttf
           weight: 700
         - asset: assets/fonts/Raleway-SemiBold.ttf
           weight: 600
