name: CI

on: [push, pull_request]

jobs:
  build:
    name: Build on Android, iOS and Mac OSX

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '1.10.x'
        channel: 'dev'
    - run: |
        cd packages/app
        flutter pub get
        flutter pub pub run build_runner build
#    - run: flutter test
        flutter build apk
        flutter build ios
        flutter build macos
