name: L.I.S.A. release CI

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build on Android, iOS and Mac OSX

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '1.10.14'
        channel: 'dev'
    - run: flutter config --no-analytics
    - run: flutter config --enable-web
    - run: flutter config --enable-macos-desktop
    - run: flutter config --enable-windows-desktop
    - run: flutter config --enable-linux-desktop
    - name: Build and test
      run: |
        cd packages/app
        flutter pub get
        flutter pub pub run build_runner build
        flutter test
    - name: Build apk
      run: |
        cd packages/app
        flutter create --org=com.mylisabox.lisa .
        flutter clean
        flutter build apk --release --split-per-abi
    - name: Create a Release APK
      uses: ncipollo/release-action@v1
      with:
        artifacts: "build/app/outputs/apk/release/*.apk"
        token: ${{ secrets.TOKEN }}
